#+TITLE: Michal Atlas

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://www.pirilampo.org/styles/bigblow/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://www.pirilampo.org/styles/bigblow/css/bigblow.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://www.pirilampo.org/styles/bigblow/css/hideshow.css"/>

#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/jquery-1.11.0.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/jquery-ui-1.10.2.min.js"></script>

#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/jquery.localscroll-min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/jquery.scrollTo-1.4.3.1-min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/jquery.zclip.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/bigblow.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/bigblow/js/hideshow.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.min.js"></script>

* Projects

- [[https://bfm.michal-atlas.xyz][Blender For Mortals]] - Guide to v2.79b Blender
- [[https://dawnstorm.michal-atlas.xyz][DawnStorm]] - 3D6 Pen & Paper RPG system
- [[https://mlxan.michal-atlas.xyz][Moonlight Xanadu]] - Some writings and stories I've been working on

* OLP

Let's talk a bit about psychology, many of you might've heard about
Synesthesia, it's when someone has two senses somewhat connected/mixed.

There are many many forms and one significantly more niche one that I
have is called Ordinal Linguistic Personification.

People with OLP assign gender and personality to many different things,
mostly though sets of arbitrary symbols, like months, days, numbers and
letters. My case excludes personality and stays perfectly static as long
as I've been aware of it. This is something that we simply feel inside
is the right thing to assign, and since they're inanimate objects I'm
fine with assuming someone's gender for once.

You might think that this could be a quirk of gendered languages, one of
which is my native tongue, however Czech assigns blanket genders to all
of these. All numbers are female, and the rest are neuter (yes, we have
3 genders).

My personification applies for a number of patterns, that I will now
list:

** Numbers
   :PROPERTIES:
   :CUSTOM_ID: numbers
   :END:

| Num | Gender |
|-----+--------|
| 1   | Female |
| 2   | Female |
| 3   | Male   |
| 4   | Female |
| 5   | Female |
| 6   | Male   |
| 7   | Female |
| 8   | Male   |
| 9   | Male   |

#+BEGIN_QUOTE
  Higher up numbers are just combinations of these digits
#+END_QUOTE

** Letters
   :PROPERTIES:
   :CUSTOM_ID: letters
   :END:

| Letter | Gender |
|--------+--------|
| A      | Female |
| B      | Female |
| C      | Male   |
| D      | Male   |
| E      | Male   |
| F      | Female |
| G      | Male   |
| H      | Female |
| I      | Female |
| J      | Female |
| K      | Female |
| L      | Female |
| M      | Female |
| N      | Male   |
| O      | Female |
| P      | Female |
| Q      | Female |
| R      | Female |
| S      | Female |
| T      | Male   |
| U      | Male   |
| V      | Female |
| W      | Female |
| X      | Male   |
| Y      | Female |
| Z      | Female |

** Days of the Week
   :PROPERTIES:
   :CUSTOM_ID: days-of-the-week
   :END:

| Day       | Gender |
|-----------+--------|
| Monday    | Female |
| Tuesday   | Male   |
| Wednesday | Female |
| Thursday  | Male   |
| Friday    | Male   |
| Saturday  | Female |
| Sunday    | Female |

* Time

#+BEGIN_EXPORT html

<div style="text-align: center; vertical-align: center">
    <hr>
        <div title="DayOfWeek | Day/Month.Quarter/Year" class="MATimer">
            <span id="MAWeekDay"></span> | 
            <span id="MADay"></span>/<span id="MAMonth"></span>/<span id="MAYear"></span>
        </div>
    <hr>
        <div class="MATimer">
            <span id="MACPOD"></span>
        </div>
    <hr>
        <div class="MATimer">
            <span id="MACFH"></span>
        </div>
    <hr>
        <div title="Hour | Minute | Second" class="MATimer">
            <span id="MACRDHour"></span><span id="MACRDMinute"></span><span id="MACRDSecond"></span>
        </div>
    <hr>
        <div class="MATimer">
            <span id="MACBUC"></span>
        </div>
    <hr>
</div>

<script>
let unifiedRay = ['0', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'Θ', 'P', 'R', 'S', 'T', 'U', 'V', 'X', 'Y', 'Z', '1', '2', '3', '4', '5', '6', '7', '8', '9', '.0', '.A', '.B', '.C', '.D', '.E', '.F', '.G', '.H', '.I', '.K', '.L', '.M', '.N', '.Θ', '.P', '.R', '.S', '.T', '.U', '.V', '.X', '.Y', '.Z', '.1', '.2', '.3', '.4', '.5', '.6', '.7', '.8', '.9'];

var t = setInterval(UpdateTime, 1000);

function UpdateTime() {
    // Single Digit Clock
    let time = new Date();
    document.getElementById("MACRDHour").innerHTML = unifiedRay[time.getHours()];
    document.getElementById("MACRDMinute").innerHTML = unifiedRay[time.getMinutes()];
    document.getElementById("MACRDSecond").innerHTML = unifiedRay[time.getSeconds()];

    // Calendar (Normalized number of Days per Month)
    day = getDayOfYear()
    if (day < 365){
        document.getElementById("MAYear").innerHTML = time.getFullYear()-1970;
        document.getElementById("MAMonth").innerHTML = Math.floor(day/28)+"."+Math.floor(day/7)%4;
        document.getElementById("MADay").innerHTML = day%28;
    }else{
        document.getElementById("MAYear").innerHTML = "";
        document.getElementById("MAMonth").innerHTML = day%2==0?"Dragonfly Festival":"Firefly Festival";
        document.getElementById("MADay").innerHTML = "";
    }
    dayName = ["Sun (Free)", "Mun", "Tas", "Wed", "Tor (Free)", "Fry", "Sut"]
    document.getElementById("MAWeekDay").innerHTML = dayName[day%7];

    Seconds = time.getSeconds() + time.getMinutes()*60 + time.getHours()*60*60;

    // Base Unicode Clock
    document.getElementById("MACBUC").innerHTML = "&#"+Seconds+";";

    // Clock % of Day
    document.getElementById("MACPOD").innerHTML = Seconds/86400*100 + "%";

    // Clock, Fraction Hours
    document.getElementById("MACFH").innerHTML = time.getHours()+"."+ Math.round(time.getMinutes()/60*100);
}

function getDayOfYear(){
    var now = new Date();
    var start = new Date(now.getFullYear(), 0, 0);
    var diff = (now - start) + ((start.getTimezoneOffset() - now.getTimezoneOffset()) * 60 * 1000);
    var oneDay = 1000 * 60 * 60 * 24;
    var day = Math.floor(diff / oneDay);
    return day;
}
</script>
<style>
    div.MATimer{
        font-size: xx-large;
    }
</style>

#+END_EXPORT
