name: Build Page

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure
        run: |
          sudo apt update
          sudo apt install emacs-nox

      - name: checkout-ox-gfm
        uses: actions/checkout@v2
        with:
          repository: 'larstvei/ox-gfm'
          path: 'ox-gfm'
          
      - name: make
        run: |
          mkdir -p build
          emacs -Q --batch -l ox-gfm/ox-gfm.el -l publishing.el --eval '(org-publish "org")'

      - name: make install
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: publish # The folder the action should deploy.
