name: Build Page

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
          
      - name: make
        run: |
          mkdir -p publish
          for f in *.org; do pandoc "$f" -s -o "publish/${f%.org}.md"; done

      - name: make install
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: publish # The folder the action should deploy.
