name: Build Page

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure
        run: |
          sudo apt update
          sudo apt install emacs
        
      - name: make
        run: |
          mkdir -p build
          emacs --batch --eval '
          (setq org-publish-project-alist
          '(("org"
          :base-directory "~/"
          :publishing-directory "~/publish"
          :publishing-function org-html-publish-to-html
          :section-numbers nil
          :with-toc t
          :html-head "<link rel=\"stylesheet\" href=\"https://cdn.simplecss.org/simple.css\">")))
          (org-publish "org")'

      - name: make install
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: publish # The folder the action should deploy.
